directories:
  output: ./out/
  buildResources: build
  app: ./dist/
appId: com.schimatos.desktop-distribution
productName: Schímatos Desktop
mac:
  target: dmg
  publish:
    - github
win:
  target: nsis
  asar: true
  publish:
    - github
linux:
  publish:
    - github
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
buildVersion: '1'
publish:
  provider: github
  always: true
  releaseType: draft
electronVersion: 12.0.1
